[package]
name = "ffi-attr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
proc-macro2 = "1.0"
ffi-attr-impl ={ path = "../ffi-attr-impl", version = "*" }